/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xinzhihui_myexplorernet_MainActivity */

#ifndef _Included_com_xinzhihui_myexplorernet_MainActivity
#define _Included_com_xinzhihui_myexplorernet_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xinzhihui_myexplorernet_MainActivity
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xinzhihui_myexplorernet_MainActivity_Init
  (JNIEnv *, jobject);

/*
 * Class:     com_xinzhihui_myexplorernet_MainActivity
 * Method:    Cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xinzhihui_myexplorernet_MainActivity_Cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_xinzhihui_myexplorernet_MainActivity
 * Method:    TestDownload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xinzhihui_myexplorernet_MainActivity_TestDownload
  (JNIEnv *, jobject);

/*
 * Class:     com_xinzhihui_myexplorernet_MainActivity
 * Method:    TestHttpPost
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xinzhihui_myexplorernet_MainActivity_TestHttpPost
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
